name: "CI: docker based builds"
on: workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - container: "opensuse/tumbleweed"
            env:
              CC: gcc
              METADATA: asciidoctor

    container:
      image: ${{ matrix.container }}
      env: ${{ matrix.env }}
      options: --privileged --security-opt seccomp=unconfined

    steps:
    - name: Install additional packages
      run: |
        set -euxo pipefail
        INSTALL=${{ matrix.container }}
        INSTALL="${INSTALL%%:*}"
        INSTALL="${INSTALL%%/*}"
        zypper --non-interactive --plus-content debug install gdb zypper-debuginfo libzypp-debuginfo
        (sleep 300; bash -c 'ls -lR /proc/*/fd; gdb -p $(pidof zypper) -ex "thread apply all bt" -ex q'; kill -9 $$) &
        zypper --non-interactive install --force-resolution --no-recommends asciidoc autoconf automake clang findutils gcc git gzip iproute2 make kernel-default-devel keyutils-devel libacl-devel libaio-devel libcap-devel libmnl-devel libnuma-devel libopenssl-devel libselinux-devel libtirpc-devel linux-glibc-devel lsb-release perl-JSON pkg-config
